// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// System information reported by the native FluidAudio runtime.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SystemInfoMessage: Hashable, CustomStringConvertible {
  /// Human-readable summary from FluidAudio's `SystemInfo.summary()`.
  var summary: String
  var isAppleSilicon: Bool
  var isIntelMac: Bool
  /// Whether Qwen3 models can run on this OS (macOS 15+ / iOS 18+).
  var qwen3Supported: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SystemInfoMessage? {
    let summary = pigeonVar_list[0] as! String
    let isAppleSilicon = pigeonVar_list[1] as! Bool
    let isIntelMac = pigeonVar_list[2] as! Bool
    let qwen3Supported = pigeonVar_list[3] as! Bool

    return SystemInfoMessage(
      summary: summary,
      isAppleSilicon: isAppleSilicon,
      isIntelMac: isIntelMac,
      qwen3Supported: qwen3Supported
    )
  }
  func toList() -> [Any?] {
    return [
      summary,
      isAppleSilicon,
      isIntelMac,
      qwen3Supported,
    ]
  }
  static func == (lhs: SystemInfoMessage, rhs: SystemInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.summary, rhs.summary) && MessagesPigeonInternal.deepEquals(lhs.isAppleSilicon, rhs.isAppleSilicon) && MessagesPigeonInternal.deepEquals(lhs.isIntelMac, rhs.isIntelMac) && MessagesPigeonInternal.deepEquals(lhs.qwen3Supported, rhs.qwen3Supported)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SystemInfoMessage")
    MessagesPigeonInternal.deepHash(value: summary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isAppleSilicon, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isIntelMac, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: qwen3Supported, hasher: &hasher)
  }

  public var description: String {
    return "SystemInfoMessage(summary: \(String(describing: summary)), isAppleSilicon: \(String(describing: isAppleSilicon)), isIntelMac: \(String(describing: isIntelMac)), qwen3Supported: \(String(describing: qwen3Supported)))"
  }
}

/// Diagnostic event used to validate the native → Dart event-channel bridge.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DebugEventMessage: Hashable, CustomStringConvertible {
  var sequence: Int64
  var message: String
  /// Optional typed-data payload (validates typed data inside event DTOs).
  ///
  /// Convention: little-endian float32 bytes. Pigeon has no Float32List type,
  /// so audio buffers cross the channel as Uint8List byte-views
  /// (`Float32List.view(bytes.buffer)` on the Dart side — no element copy).
  var payload: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DebugEventMessage? {
    let sequence = pigeonVar_list[0] as! Int64
    let message = pigeonVar_list[1] as! String
    let payload: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return DebugEventMessage(
      sequence: sequence,
      message: message,
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      sequence,
      message,
      payload,
    ]
  }
  static func == (lhs: DebugEventMessage, rhs: DebugEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sequence, rhs.sequence) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.payload, rhs.payload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DebugEventMessage")
    MessagesPigeonInternal.deepHash(value: sequence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: payload, hasher: &hasher)
  }

  public var description: String {
    return "DebugEventMessage(sequence: \(String(describing: sequence)), message: \(String(describing: message)), payload: \(String(describing: payload)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SystemInfoMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return DebugEventMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SystemInfoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DebugEventMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SystemHostApi {
  func systemInfo(completion: @escaping (Result<SystemInfoMessage, Error>) -> Void)
  /// Round-trips a float32-bytes buffer across the channel (typed-data probe).
  func echoFloats(samples: FlutterStandardTypedData, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Emits [count] events on the `debugEvents` stream (event-channel probe).
  func debugEmitEvents(count: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SystemHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SystemHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SystemHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let systemInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fluidaudio_dart.SystemHostApi.systemInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      systemInfoChannel.setMessageHandler { _, reply in
        api.systemInfo { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      systemInfoChannel.setMessageHandler(nil)
    }
    /// Round-trips a float32-bytes buffer across the channel (typed-data probe).
    let echoFloatsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fluidaudio_dart.SystemHostApi.echoFloats\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      echoFloatsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let samplesArg = args[0] as! FlutterStandardTypedData
        api.echoFloats(samples: samplesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      echoFloatsChannel.setMessageHandler(nil)
    }
    /// Emits [count] events on the `debugEvents` stream (event-channel probe).
    let debugEmitEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fluidaudio_dart.SystemHostApi.debugEmitEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugEmitEventsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        api.debugEmitEvents(count: countArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      debugEmitEventsChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class DebugEventsStreamHandler: PigeonEventChannelWrapper<DebugEventMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: DebugEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.fluidaudio_dart.FluidAudioEventChannelApi.debugEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<DebugEventMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
